package net.tiffit.wynnforge.wynnapi.items;

public class WynnItem {

	public String name;
	public String tier;
	public String set;
	public int sockets;
	public String type;
	public String addedLore;
	public String material;
	public String dropType;
	public String restrictions;
	public String damage;
	public String fireDamage;
	public String waterDamage;
	public String airDamage;
	public String thunderDamage;
	public String earthDamage;
	public String attackSpeed;
	public int level;
	public String quest;
	public int strength;
	public int dexterity;
	public int intelligence;
	public int agility;
	public int defense;
	public int healthRegen;
	public int manaRegen;
	public int spellDamage;
	public int damageBonus;
	public int lifeSteal;
	public int manaSteal;
	public int xpBonus;
	public int lootBonus;
	public int reflection;
	public int strengthPoints;
	public int dexterityPoints;
	public int intelligencePoints;
	public int agilityPoints;
	public int defensePoints;
	public int thorns;
	public int exploding;
	public int speed;
	public int attackSpeedBonus;
	public int poison;
	public int healthBonus;
	public int soulPoints;
	public int emeraldStealing;
	public int healthRegenRaw;
	public int spellDamageRaw;
	public int damageBonusRaw;
	public int bonusFireDamage;
	public int bonusWaterDamage;
	public int bonusAirDamage;
	public int bonusThunderDamage;
	public int bonusEarthDamage;
	public int bonusFireDefense;
	public int bonusWaterDefense;
	public int bonusAirDefense;
	public int bonusThunderDefense;
	public int bonusEarthDefense;
	public String category;
	
}
